/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'maet-bg-deep': 'var(--maet-bg-deep)',
        'maet-bg-night': 'var(--maet-bg-night)',
        'maet-bg-ink': 'var(--maet-bg-ink)',
        'maet-bg-panel': 'var(--maet-bg-panel)',
        'maet-bg-soft': 'var(--maet-bg-soft)',
        'maet-glass-1': 'var(--maet-glass-1)',
        'maet-glass-2': 'var(--maet-glass-2)',
        'maet-glass-3': 'var(--maet-glass-3)',
        'maet-glass-border': 'var(--maet-glass-border)',
        'maet-glass-border-strong': 'var(--maet-glass-border-strong)',
        'maet-text-main': 'var(--maet-text-main)',
        'maet-text-soft': 'var(--maet-text-soft)',
        'maet-text-faint': 'var(--maet-text-faint)',
        'maet-cyan': 'var(--maet-cyan)',

        'maet-void': 'var(--bg-void)',
        'maet-base': 'var(--bg-base)',
        'maet-surface': 'var(--bg-surface)',
        'maet-elevated': 'var(--bg-elevated)',
        'maet-overlay': 'var(--bg-overlay)',
        'maet-border': 'var(--border-subtle)',
        'maet-border-strong': 'var(--border-strong)',
        'maet-text': 'var(--text-primary)',
        'maet-text-secondary': 'var(--text-secondary)',
        'maet-text-muted': 'var(--text-muted)',
        'maet-green': 'var(--accent-green)',
        'maet-red': 'var(--accent-red)',
        'maet-amber': 'var(--accent-amber)',
        'maet-blue': 'var(--accent-blue)',
        'maet-blue-strong': 'var(--maet-blue-strong)',
        'maet-violet': 'var(--accent-violet)',
        'safety-locked': 'var(--safety-locked)',
        'safety-paper': 'var(--safety-paper)',
        'safety-read': 'var(--safety-read)',
        'safety-ai': 'var(--safety-ai)',
        'safety-broker': 'var(--safety-broker)',

        // Existing aliases kept for legacy components.
        bg: 'var(--bg)',
        'bg-2': 'var(--bg-2)',
        'bg-surface': 'var(--bg-surface)',
        panel: 'var(--panel)',
        'panel-2': 'var(--panel-2)',
        'panel-3': 'var(--panel-3)',
        border: 'var(--border)',
        'border-strong': 'var(--border-strong)',
        'border-accent': 'var(--border-accent)',
        'border-card': 'var(--border-card)',
        text: 'var(--text)',
        'text-2': 'var(--text-2)',
        'text-dim': 'var(--text-dim)',
        'text-faint': 'var(--text-faint)',
        up: 'var(--up)',
        'up-dim': 'var(--up-dim)',
        down: 'var(--down)',
        'down-dim': 'var(--down-dim)',
        warn: 'var(--warn)',
        'warn-dim': 'var(--warn-dim)',
        info: 'var(--info)',
        'info-dim': 'var(--info-dim)',
        locked: 'var(--locked)',
        violet: 'var(--violet)',
        paper: 'var(--paper)',
        live: 'var(--live)',
      },
      fontFamily: {
        sans: ['var(--font-sans)', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        heading: ['var(--font-heading)', 'var(--font-sans)', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        mono: ['var(--font-mono)', 'ui-monospace', 'JetBrains Mono', 'monospace'],
      },
      fontSize: {
        '2xs': ['10px', { lineHeight: '14px' }],
        xs: ['11px', { lineHeight: '16px' }],
        sm: ['12px', { lineHeight: '18px' }],
        base: ['14px', { lineHeight: '20px' }],
        md: ['15px', { lineHeight: '22px' }],
        lg: ['16px', { lineHeight: '24px' }],
        xl: ['18px', { lineHeight: '26px' }],
        '2xl': ['20px', { lineHeight: '28px' }],
        '3xl': ['24px', { lineHeight: '32px' }],
        '4xl': ['32px', { lineHeight: '40px' }],
        '5xl': ['40px', { lineHeight: '48px' }],
      },
      spacing: {
        nav: 'var(--bottom-nav-h)',
        header: 'var(--top-header-h)',
        safety: 'var(--safety-strip-h)',
        'safe-b': 'env(safe-area-inset-bottom, 0px)',
      },
      borderRadius: {
        card: '16px',
        card2: '20px',
        pill: '100px',
      },
      boxShadow: {
        card: 'var(--maet-shadow-card)',
        glass: 'var(--maet-shadow-glass)',
        raised: 'var(--shadow-raised)',
        inner: 'var(--maet-shadow-inner)',
        modal: '0 32px 80px rgba(0,0,0,0.7), 0 0 0 1px var(--maet-glass-border-strong)',
        up: '0 0 16px rgba(22, 199, 132, 0.24)',
        down: '0 0 16px rgba(234, 57, 67, 0.24)',
        cyan: '0 0 20px rgba(34, 211, 238, 0.24)',
      },
      borderWidth: {
        3: '3px',
      },
      animation: {
        'pulse-soft': 'pulseSoft 2.4s ease-in-out infinite',
        'flash-up': 'tickUp 0.6s ease-out',
        'flash-down': 'tickDown 0.6s ease-out',
        'slide-up': 'slideInBottom 0.2s ease-out',
        'fade-in': 'fadeIn 0.15s ease-out',
      },
      keyframes: {
        pulseSoft: {
          '0%, 100%': { opacity: '0.55' },
          '50%': { opacity: '1' },
        },
        tickUp: {
          '0%': { backgroundColor: 'rgba(22,199,132,0.24)' },
          '100%': { backgroundColor: 'transparent' },
        },
        tickDown: {
          '0%': { backgroundColor: 'rgba(234,57,67,0.22)' },
          '100%': { backgroundColor: 'transparent' },
        },
        slideInBottom: {
          from: { transform: 'translateY(100%)', opacity: '0' },
          to: { transform: 'translateY(0)', opacity: '1' },
        },
        fadeIn: {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
      },
    },
  },
  plugins: [],
}
