import { useTerminalStore } from './terminal-store-core'
import type { TerminalStore } from './terminal-store-core'

export type MarketStore = Pick<
  TerminalStore,
  | 'activeSym'
  | 'selectedSymbol'
  | 'selectedExchange'
  | 'selectedInstrumentName'
  | 'selectedInstrumentToken'
  | 'selectedInstrumentSource'
  | 'lastSelectedAt'
  | 'selectedWatchlistId'
  | 'watchlistGroupId'
  | 'watchlistGroups'
  | 'marketWatch'
  | 'indices'
  | 'watchlistSource'
  | 'watchlistLoading'
  | 'watchlistError'
  | 'watchlistAdminRequired'
  | 'watchlistLastUpdatedAt'
  | 'currentTick'
  | 'lastTickAt'
  | 'lastTickBySymbol'
  | 'dataQualityBySymbol'
  | 'tickCount'
  | 'chartTimeframe'
  | 'chartCandlesBySymbolTimeframe'
  | 'chartFetchDiagnostics'
  | 'setSelectedSymbol'
  | 'setActiveSym'
  | 'setSelectedInstrument'
  | 'openChartForInstrument'
  | 'clearSelectedInstrument'
  | 'setSelectedWatchlist'
  | 'setWatchlistGroup'
  | 'addToWatchlist'
  | 'removeFromWatchlist'
  | 'ingestMarketWatchRows'
  | 'setIndices'
  | 'ingestTick'
  | 'incTickCount'
  | 'fetchPersistentWatchlist'
  | 'addSymbolToBackend'
  | 'removeSymbolFromBackend'
  | 'fetchChartIndicators'
  | 'clearChartIndicators'
  | 'setChartTimeframe'
>

export function useMarketStore<T>(selector: (state: MarketStore) => T): T {
  return useTerminalStore(selector as (state: TerminalStore) => T)
}
