"""add_user_id_to_watchlists

Revision ID: 49b0deddd21c
Revises: 5a5f46a0a5c2
Create Date: 2026-05-26 12:39:44.827788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49b0deddd21c'
down_revision: Union[str, None] = '5a5f46a0a5c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchlists', sa.Column('user_id', sa.String(), nullable=False))
    op.drop_index('ix_watchlists_name', table_name='watchlists')
    op.create_index(op.f('ix_watchlists_name'), 'watchlists', ['name'], unique=False)
    op.create_index(op.f('ix_watchlists_user_id'), 'watchlists', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlists_user_id'), table_name='watchlists')
    op.drop_index(op.f('ix_watchlists_name'), table_name='watchlists')
    op.create_index('ix_watchlists_name', 'watchlists', ['name'], unique=1)
    op.drop_column('watchlists', 'user_id')
    # ### end Alembic commands ###
