"""add_sector_to_instruments

Revision ID: 5a5f46a0a5c2
Revises: 40478e2b5418
Create Date: 2026-05-26 12:25:03.985031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a5f46a0a5c2'
down_revision: Union[str, None] = '40478e2b5418'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instruments', sa.Column('sector', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instruments', 'sector')
    # ### end Alembic commands ###
