"""add_live_approval_intent

Revision ID: b16d89160387
Revises: 8ef7a68bc69b
Create Date: 2026-05-28 01:08:58.268785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b16d89160387'
down_revision: Union[str, None] = '8ef7a68bc69b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('live_approval_intents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('intent_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('product_type', sa.String(), nullable=False),
    sa.Column('order_type', sa.String(), nullable=False),
    sa.Column('source_signal_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('validation_summary', sa.String(), nullable=False),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_live_approval_intents_intent_id'), 'live_approval_intents', ['intent_id'], unique=True)
    op.create_index(op.f('ix_live_approval_intents_symbol'), 'live_approval_intents', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_live_approval_intents_symbol'), table_name='live_approval_intents')
    op.drop_index(op.f('ix_live_approval_intents_intent_id'), table_name='live_approval_intents')
    op.drop_table('live_approval_intents')
    # ### end Alembic commands ###
