"""create_manual_order_tickets

Revision ID: d64dcb818e3b
Revises: b16d89160387
Create Date: 2026-05-28 02:18:00.313621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd64dcb818e3b'
down_revision: Union[str, None] = 'b16d89160387'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manual_order_tickets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('exchange', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('product_type', sa.String(), nullable=False),
    sa.Column('order_type', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('estimated_notional', sa.Float(), nullable=True),
    sa.Column('price_source', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('validation_summary', sa.String(), nullable=False),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manual_order_tickets_ticket_id'), 'manual_order_tickets', ['ticket_id'], unique=True)
    op.create_index(op.f('ix_manual_order_tickets_symbol'), 'manual_order_tickets', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_manual_order_tickets_symbol'), table_name='manual_order_tickets')
    op.drop_index(op.f('ix_manual_order_tickets_ticket_id'), table_name='manual_order_tickets')
    op.drop_table('manual_order_tickets')
    # ### end Alembic commands ###
